POST localhost:8080/assinantes/pessoaJuridica
Content-Type: application/json


{"nome": "DR. Pimpolho", "cnpj": "000.000.000-00", "planoDTO": {"id": 1}, "nome":"Cileide dos Santos","cnpj": "000.000.000-00"}